baseURL = "https://pages.cs.wisc.edu/~gleicher/"
languageCode = "en-us"
title = "Michael Gleicher's Web Page"

theme = ["559Theme","mainroad"]
paginate = 12

relativeURLs = true
canonifyURLs = true
enableGitInfo = true

[[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -1000

[[menu.main]]
    identifier = "Papers"
    name = "Papers"
    url = "https://graphics.cs.wisc.edu/Papers/?author=Gleicher"
    weight = 10

[[menu.main]]
    identifier = "Talks"
    name = "Talks"
    url = "/talks"
    weight = 100

[[menu.main]]
    identifier = "Videos"
    name = "Videos"
    url = "/video"
    weight = 110

[[menu.main]]
    identifier = "Advice"
    name = "Advice"
    url = "/pages/advice"
    weight = 150

[Params]
post_meta = ["date","taglist","categories"]
mainSections = ["main"]
dateformat = "January, 2006"
copyright = "Michael Gleicher"
# subtitle = "Michael Gleicher's Web Page"
customCss = ["css/home.scss"]

[Params.sidebar]
home = "right"
list = "right"
single = "right"
widgets = ["lunr","sections","links","categories","taglist"]


[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true
