# note: this builds github pages on a DIFFERENT repo
# (my "home" repo)
# see https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-deploy-to-external-repository-external_repository
name: github pages

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

# checkout: https://github.com/actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          # this shouldn't need any private repos - so no personal token
          token: ${{ secrets.GITHUB_TOKEN }}
          # token: ${{ secrets.PERSONAL_TOKEN }}
          # ssh-key: ${{ secrets.DEPLOY_READ_KEY }}

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.152.2'  # Set the Hugo version
          extended: true

      - name: Build
        run: hugo --minify --baseURL="https://gleicher.sites.cs.wisc.edu/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/master'
        with:
          # personal_token: ${{ secrets.PERSONAL_TOKEN }}
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          allow_empty_commit: true
          enable_jekyll: false
          publish_branch: gh-pages
          external_repository: gleicher/gleicher.github.io
